# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  emacsng = {
    pname = "emacsng";
    version = "c18470efe98a3ec33ff18561377548527140cb27";
    src = fetchFromGitHub ({
      owner = "declantsien";
      repo = "emacs-ng";
      rev = "c18470efe98a3ec33ff18561377548527140cb27";
      fetchSubmodules = true;
      sha256 = "sha256-QTxD6c+nu9ajsiJOqsH3YJXQ9r/ryrTB28uWskKuLJ4=";
    });
  };
}
