# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  emacs-webrender = {
    pname = "emacs-webrender";
    version = "2407f974a176839885d56f050750d4c4ce661b04";
    src = fetchFromGitHub ({
      owner = "declantsien";
      repo = "emacs-ng";
      rev = "2407f974a176839885d56f050750d4c4ce661b04";
      fetchSubmodules = false;
      sha256 = "sha256-jg4fbJFPiu1XNCU7Zh6L00m8iZ+4uduXIiDep95zaHA=";
    });
  };
}
