# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  emacs-webrender = {
    pname = "emacs-webrender";
    version = "831e9911065662ef6e194b090a6a5fa2a587683a";
    src = fetchFromGitHub ({
      owner = "declantsien";
      repo = "emacs-ng";
      rev = "831e9911065662ef6e194b090a6a5fa2a587683a";
      fetchSubmodules = false;
      sha256 = "sha256-60k7vjqdW1s4CFqDGD5Ckf/kfuuc6iQ/N1u2CScG/mQ=";
    });
  };
}
