---
name: macOS dmg
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
    inputs:
      git_sha:
        description: Override Emacs git commit SHA to build
        required: false

jobs:
  prepare:
    name: Prepare
    uses: ./.github/workflows/_prepare.yml
    secrets:
      TAP_REPO_TOKEN: ${{ secrets.TAP_REPO_TOKEN }}

  build:
    name: Build
    needs: [prepare]
    uses: ./.github/workflows/_build.yml
    with:
      os: macos-11
      git_ref: vendor-master
      git_sha: ${{ github.event.inputs.git_sha }}
      build_args: --native-comp
    secrets:
      APPLE_DEVELOPER_CERTIFICATE_P12_BASE64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
      APPLE_DEVELOPER_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      AC_USERNAME: ${{ secrets.AC_USERNAME }}
      AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
      AC_PROVIDER: ${{ secrets.AC_PROVIDER }}
      AC_SIGN_IDENTITY: ${{ secrets.AC_SIGN_IDENTITY }}
      TAP_REPO_TOKEN: ${{ secrets.TAP_REPO_TOKEN }}

  release:
    name: Release
    needs: [build]
    # Only run if check for existing release and asset failed.
    if: ${{ needs.build.plan.outputs.check == 'fail' }}
    uses: ./.github/workflows/_release.yml
    with:
      plan_artifact: build-plan
      dmg_artifact: dmg
    secrets:
      TAP_REPO_TOKEN: ${{ secrets.TAP_REPO_TOKEN }}
